### ISSUE TITLE
SetTitle doesn't work?

### ISSUE THREAD

**Issue by Jackson0111** [yannickl/DynamicButton#1]
Hi! I appreciate your work and I'm loving it! But I've been struggling to set title for a button, here's my code but it's not working.

```
    let confirm_button = DynamicButton()

    confirm_button.setTitle("Confirm", forState: .Normal)

    confirm_button.setTitleColor(UIColor.blackColor(), forState: .Normal)

    confirm_button.backgroundColor = UIColor.bluecolor()
```

The above code executes perfectly but the button only shows background color but not the title. Is there a way to to so?

**Comment by yannickl** [comment]
Hi,

This is normal, because I override the method in order to avoid the text display over the lines.

Why do you want to set the title over?

**Comment by Jackson0111** [comment]
I just like the pop animation when button is clicked so I wanna set it up for all my buttons.

**Comment by yannickl** [comment]
I see, if you want to display the title you should remove these lines: https://github.com/yannickl/DynamicButton/blob/master/DynamicButton/DynamicButton.swift#L138-L140.

I think in your case the most simple is to create your own subclass with the needed features?

**Comment by Jackson0111** [comment]
Yes it would be a great idea but I'm not very good with coding animations... Any help on that maybe?

**Comment by yannickl** [comment]
The animations are very simple. Just check these lines: https://github.com/yannickl/DynamicButton/blob/master/DynamicButton/DynamicButton.swift#L271-L293.

When the button is pushed the `highlightAction` is called and when touche leaves this is the `unhighlightAction` turn (https://github.com/yannickl/DynamicButton/blob/master/DynamicButton/DynamicButton.swift#L154-L158).

I hope it'll help.

**Comment by Jackson0111** [comment]
Thank you! I will look into that!
