### ISSUE TITLE
DynamicButtonPathVector

### ISSUE THREAD

**Issue by franck-nadeau** [yannickl/DynamicButton#19]
Creating a custom DynamicButtonBuildableStyle in Swift 4 yields the following compile error:

```
'DynamicButtonPathVector' initializer is inaccessible due to 'internal' protection level
```
 When trying to create a DynamicButtonPathVector(p1: CGMutablePath(), p2: CGMutablePath(), p3: CGMutablePath(), p4: CGMutablePath())

I have a fix for this and I will send a PR for it.

**Comment by yannickl** [comment]
This is now merged.
