### ISSUE TITLE
Hamburger icon with rounded tips

### ISSUE THREAD

**Issue by rpelorosso** [yannickl/DynamicButton#21]
Hi!

I'm creating a hamburger button using

``` 
button = DynamicButton(frame: CGRect(x: 0, y: 0, width: 30, height: 30))
button.lineWidth = 4
button.setStyle(.hamburger, animated: false)
 ```

Now, the Hamburger has square tips,

![image](https://user-images.githubusercontent.com/6107574/42972601-6f13246c-8b86-11e8-95ce-bc7f6470e5da.png)

but the Close icon has rounded tips

![image](https://user-images.githubusercontent.com/6107574/42972645-7fec3d32-8b86-11e8-947e-cc9e00449d75.png)

The documentation shows a hamburger icon with rounded tips, so I'm wondering. Am I doing something wrong? or is there something I can set in order to achieve that?

thank you!

**Comment by yannickl** [comment]
Hi @rpelorosso,

Thank you for reporting this. 👍 I hadn't noticed this, but indeed there was a glitch in some button styles because the rounded tips were clipped by the component. So I've updated the styles to avoid this issues.
