### ISSUE TITLE
DynamicButton.Style needs a hash(into:) method to conform to Hashable

### ISSUE THREAD

**Issue by howardck** [yannickl/DynamicButton#24]
The compiler's reporting the following problem:

/Users/hkatz/DynamicButton/Sources/DynamicButtonStyle.swift:177:14: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'DynamicButton.Style' to 'Hashable' by implementing 'hash(into:)' instead

I think I could likely fix this and do a pull request on it, but I've never done that and don't have the time at the moment to figure it out. Soon tho! :-)

**Comment by yannickl** [comment]
Thank you @howardck for pointing me this! I'm going to push an update. 👍
