### ISSUE TITLE
Custom button symbols

### ISSUE THREAD

**Issue by cannyboy** [yannickl/DynamicButton#3]
It would be nice to be able to create custom buttons, perhaps with a function that can be fed `CGPathRef`s:

```
let startCustomButton = DynamicButton(startLine1, startLine2, startLine3, startLine4)
let endCustomButton = DynamicButton(endLine1, endLine2, endLine3, endLine4)

startCustomButton.setStyle(endCustomButton.style, animated: true)
```

( maybe even use ASCIImage  - https://github.com/cparnot/ASCIImage/issues/12 )

**Comment by yannickl** [comment]
This is a good idea! 👍 

I don't have time for the moment, but I'll see during the next w-e what I can do. (Of course, If you have time, you are welcomed)

**Comment by yannickl** [comment]
You can now create your own symbols! You have to use the v2.x branch however.

**Comment by cannyboy** [comment]
great, looks good.

![clock-target](https://cloud.githubusercontent.com/assets/1590436/14711140/273f3f2c-07d0-11e6-8a92-cd0fc3cb5240.gif)
