### ISSUE TITLE
PathHelper is unresolved

### ISSUE THREAD

**Issue by protspace** [yannickl/DynamicButton#9]
`Use of unresolved identifier 'PathHelper'`
when I'm trying to call 
`PathHelper.line(atCenter: center, radius: size / 2, angle: PathHelper.F_PI_2)`
Xcode 8, Swift 3, 1.1.0.rc2

**Comment by yannickl** [comment]
The `PathHelper` is not public. I use it internally to help me to build paths.

I updated the readme to remove the reference to this class.
